# Generated by Django 5.1.4 on 2025-01-16 09:11

import mycontazapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone_number', models.IntegerField(blank=True, max_length=10, null=True, unique=True)),
                ('gender', models.CharField(blank=True, null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(default='contact/default.png', upload_to=mycontazapp.models.contact_image)),
            ],
        ),
    ]
