# Generated by Django 5.1.4 on 2025-01-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycontazapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='mycontazapp.category'),
        ),
    ]
